
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 151
#define YY_END_OF_BUFFER 152
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[514] =
    {   0,
        0,    0,  152,  147,  150,  147,  146,  147,  147,   32,
      147,  147,   63,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   82,   99,   97,   84,   70,   85,   86,   87,
       75,   88,   89,   90,  101,  100,   76,   77,   68,   71,
       83,   72,   74,   98,   69,   96,   73,   95,  147,    1,
        2,  147,  147,    0,  143,  146,  146,  147,  147,    0,
      144,  141,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,   41,
       42,   43,   44,   45,   46,   47,   48,   49,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,

      147,  147,  147,    8,    9,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  120,
      147,  147,    0,  145,  143,  147,  144,  147,    0,  147,
      147,    0,  149,  142,  147,  147,    6,  147,  147,  147,
      147,    5,  147,  147,  147,   13,  147,    7,  118,  147,
      147,   40,    4,   50,   51,   52,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,   67,  147,  147,  147,  147,  145,   14,    0,  147,

      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      121,  147,  147,  147,  115,  147,  122,  147,  147,  147,
      147,  147,  147,  147,  147,  112,  147,  147,  147,  147,
      147,  147,  147,  116,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,   91,  147,  147,  147,  147,
      147,  147,  147,  147,  148,  147,  147,  147,  147,  147,
      147,  147,  102,  147,  147,  147,   80,  147,   65,  147,
      147,  147,  147,  108,  147,  147,  107,  147,   64,  147,
       10,  147,  139,  135,  136,  137,  132,  133,  134,  128,
      129,  130,  147,  147,  147,  147,  147,  147,  147,  147,

      103,  147,   92,  123,  147,  110,  147,  147,  111,  147,
      147,  147,  104,  109,  147,  147,  147,    3,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  117,
      147,  114,   37,  147,  147,  106,  147,  147,   38,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  119,
      147,   39,  113,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,   15,  147,  147,  147,
       53,   11,  147,  147,   12,   93,  147,  147,  147,  147,
      147,  147,  140,  147,  147,  147,  126,  147,  147,  147,
      147,   94,  147,  147,  147,  147,  147,  147,  147,  147,

      147,  147,  147,  147,  147,  147,  147,  147,   20,  147,
      147,  147,  147,   33,  147,  147,  124,  147,  131,  147,
       78,  147,   17,  147,  147,  147,  147,  147,  147,   26,
      147,  147,  105,   66,  147,   81,   79,  147,  147,  147,
      147,  147,  147,  138,  127,  125,  147,  147,  147,  147,
       18,  147,  147,  147,   25,  147,   16,  147,   34,   35,
      147,  147,  147,  147,  147,  147,  147,  147,   30,  147,
      147,   36,   28,  147,  147,  147,  147,  147,  147,  147,
      147,  147,   19,   29,  147,  147,  147,   27,   31,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,

      147,  147,  147,   21,  147,  147,  147,   23,  147,   22,
      147,   24,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    1,    1,    8,    1,
        1,    9,   10,    1,   10,    1,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,    1,    1,    1,
        1,    1,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,    1,   49,    1,   50,    1,   51,   51,   51,   51,

       51,   51,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   52,
        1,    1,   53,    1,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[55] =
    {   0,
        1,    2,    2,    3,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[527] =
    {   0,
        0,    0,  626,    0,  627,   51,   53,  597,   55,    0,
       52,   65,   65,  572,  571,  570,  569,  568,  567,  566,
      565,  564,  573,   65,   66,   64,   63,  105,    0,  578,
      578,    0,    0,  101,  106,  570,  574,   78,  568,   79,
      108,   85,  572,  578,    0,    0,    0,    0,  126,    0,
        0,    0,   57,  602,    0,  100,    0,  564,  142,  597,
        0,  552,  150,  154,  164,  562,   71,  578,  127,  565,
      127,   83,  561,  555,  571,  167,  555,  572,  569,  153,
        0,    0,    0,    0,    0,    0,    0,    0,  560,  553,
      565,  555,  562,  554,  172,  553,  552,  551,  549,  542,

      550,  548,  555,    0,    0,  168,  133,  544,  551,  542,
      173,  135,  542,  554,  553,  552,  550,  527,  164,    0,
      534,  195,  521,  197,  627,  539,  627,  216,  559,  224,
      168,  564,  627,    0,  530,  533,    0,  528,  530,  522,
      521,  526,  519,  536,  531,    0,  521,    0,    0,  183,
      533,    0,    0,    0,    0,    0,  528,  527,  511,  509,
      514,  525,  515,  506,  517,  515,  502,  501,  500,  499,
      500,  498,  488,  502,  500,  498,  499,  503,  491,  502,
      488,  496,  487,  498,  496,  182,  495,  496,  483,  498,
      482,    0,  479,  493,  485,  480,  467,    0,  504,    0,

      193,  474,  480,  482,  461,  484,  487,  472,  465,  465,
        0,  466,  458,  470,    0,  463,    0,  461,  469,  470,
      457,  458,  466,  460,  472,    0,  453,  452,  465,  460,
      235,  439,  444,    0,  446,  445,  459,  443,  443,  441,
      442,  450,  444,  442,  451,    0,  443,  446,  448,  432,
      448,  421,  444,  430,  627,  438,  441,  170,  430,  440,
      431,  413,    0,  429,  428,  434,    0,  435,    0,  417,
      431,  419,  429,    0,  421,  426,    0,  419,    0,  425,
      400,  412,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  422,  412,  410,  194,  412,  411,  403,  407,

        0,  411,    0,    0,  414,    0,  406,  411,    0,  404,
      391,  409,    0,    0,  394,  397,  392,  381,  394,  405,
      395,  405,  404,  386,  382,  387,  382,  395,  379,    0,
      383,    0,    0,  392,  378,    0,  375,  378,    0,  232,
      381,  380,  371,  387,  375,  376,  366,  385,  368,    0,
      369,    0,    0,  363,  367,  361,  364,  350,  366,  362,
      357,  355,  354,  358,  353,  368,    0,  351,  366,  351,
        0,    0,  355,  359,    0,    0,  356,  349,  358,  353,
      345,  359,    0,  354,  347,  336,    0,  337,  336,  352,
      339,    0,  334,  348,  338,  330,  333,  329,  331,  330,

      323,  342,  334,  336,  337,  328,  336,  322,    0,  333,
      312,  328,  326,    0,  307,  313,    0,  311,    0,  321,
        0,  299,    0,  312,  325,  310,  306,  303,  304,    0,
      303,  316,    0,    0,  307,    0,    0,  300,  297,  302,
      295,  306,  308,    0,    0,    0,  293,  299,  285,  291,
        0,  279,  287,  301,    0,  290,    0,  283,    0,    0,
      283,  276,  268,  265,  271,  252,  245,  235,    0,  239,
      239,    0,    0,  238,  234,  231,  217,  240,  220,  238,
      236,  218,    0,    0,  214,  215,  217,    0,    0,  192,
      215,  212,  209,  194,  207,  205,  205,  205,  186,  170,

      175,  144,  115,    0,   98,  105,   56,    0,   60,    0,
       34,    0,  627,  275,  279,  283,  287,  291,  295,  299,
      302,  305,  309,  313,  316,  319
    } ;

static yyconst flex_int16_t yy_def[527] =
    {   0,
      513,    1,  513,  514,  513,  515,  516,  514,  517,  514,
      514,  514,  514,   13,   13,   13,   13,   13,   13,   13,
       13,   13,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  518,  514,
      514,  514,  515,  519,  514,  516,  520,  514,  517,  521,
      514,   13,  522,  523,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,

      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  518,  524,  518,  513,  514,  513,  522,  525,  522,
      523,  526,  513,   65,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  524,  514,  525,  514,

      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  513,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,

      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,

      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,

      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,
      514,  514,    0,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513
    } ;

static yyconst flex_int16_t yy_nxt[682] =
    {   0,
        4,    5,    5,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,    4,    4,
        4,    4,   50,   51,   54,   55,   57,   52,   60,   52,
       54,   55,   61,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   63,  512,   64,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   67,   69,  511,   72,
      104,  105,   68,   73,  136,   75,  510,   76,   70,   74,

       77,   71,   78,   57,   52,  106,  117,   79,  109,  144,
      118,  137,  110,  107,  119,  145,   65,   80,   81,   82,
       83,   84,   85,   86,   87,   88,   91,   96,  111,  123,
       52,   97,  509,  112,   92,   98,   93,  113,  508,   99,
      114,  100,   94,  507,  115,   60,   52,  101,  116,   61,
       95,  129,  129,  129,   52,  132,  133,  132,  130,  139,
      142,  143,  177,  140,  154,  155,  156,  186,  187,  132,
      133,  132,  178,  506,  124,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  149,  175,  163,  182,  164,  183,  194,  123,   52,

      123,   52,  322,  505,  195,  244,  323,  150,  212,  176,
      504,  165,  184,  503,  134,  166,  185,  129,  129,  129,
       52,  213,  245,  345,  130,  129,  129,  129,   52,  256,
      502,  257,  501,  500,  200,  346,  499,  498,  497,  496,
      495,  494,  493,  124,  492,  124,  283,  284,  285,  286,
      287,  288,  289,  290,  291,  292,  378,  491,  490,  293,
      294,  489,  488,  487,  379,  486,  485,  295,  296,  484,
      380,  297,  483,  381,  298,   52,  482,  481,   52,   53,
      480,   53,   53,   56,  479,   56,   56,   59,  478,   59,
       59,  122,  477,  122,  122,   54,  476,   54,   54,   57,

      475,   57,   60,  474,   60,  128,  128,  128,  128,  131,
      131,  131,  131,  123,  473,  123,  129,  129,  129,  132,
      132,  132,  132,  472,  471,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,  460,  459,  458,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  437,  436,
      435,  434,  433,  432,  431,  430,  429,  428,  427,  426,
      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,

      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  377,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  367,  366,  365,  364,  363,  362,
      361,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  347,  344,  343,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,

      271,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  255,  197,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  133,  199,  198,  197,
      196,  193,  192,  191,  190,  189,  188,  181,  180,  179,
      174,  173,  172,  171,  170,  169,  168,  167,  162,  161,
      160,  159,  158,  157,  153,  152,  151,  148,  147,  146,

      141,  138,  135,   52,  127,  126,  125,  121,  120,  108,
      103,  102,   90,   89,   66,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   58,  513,    3,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513
    } ;

static yyconst flex_int16_t yy_chk[682] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    6,    7,    7,    9,    9,
       53,   53,    9,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   12,  511,   12,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   24,   25,  509,   26,
       38,   38,   24,   26,   67,   27,  507,   27,   25,   26,

       27,   25,   27,   56,   56,   38,   42,   27,   40,   72,
       42,   67,   40,   38,   42,   72,   13,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   34,   35,   40,   49,
       49,   35,  506,   41,   34,   35,   34,   41,  505,   35,
       41,   35,   34,  503,   41,   59,   59,   35,   41,   59,
       34,   63,   63,   63,   63,   64,   64,   64,   63,   69,
       71,   71,  107,   69,   80,   80,   80,  112,  112,  131,
      131,  131,  107,  502,   49,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   76,  106,   95,  111,   95,  111,  119,  122,  122,

      124,  124,  258,  501,  119,  186,  258,   76,  150,  106,
      500,   95,  111,  499,   65,   95,  111,  128,  128,  128,
      128,  150,  186,  296,  128,  130,  130,  130,  130,  201,
      498,  201,  497,  496,  130,  296,  495,  494,  493,  492,
      491,  490,  487,  122,  486,  124,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  340,  485,  482,  231,
      231,  481,  480,  479,  340,  478,  477,  231,  231,  476,
      340,  231,  475,  340,  231,  514,  474,  471,  514,  515,
      470,  515,  515,  516,  468,  516,  516,  517,  467,  517,
      517,  518,  466,  518,  518,  519,  465,  519,  519,  520,

      464,  520,  521,  463,  521,  522,  522,  522,  522,  523,
      523,  523,  523,  524,  462,  524,  525,  525,  525,  526,
      526,  526,  526,  461,  458,  456,  454,  453,  452,  450,
      449,  448,  447,  443,  442,  441,  440,  439,  438,  435,
      432,  431,  429,  428,  427,  426,  425,  424,  422,  420,
      418,  416,  415,  413,  412,  411,  410,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  391,  390,  389,  388,  386,  385,  384,
      382,  381,  380,  379,  378,  377,  374,  373,  370,  369,
      368,  366,  365,  364,  363,  362,  361,  360,  359,  358,

      357,  356,  355,  354,  351,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  338,  337,  335,  334,  331,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  312,  311,  310,  308,  307,  305,
      302,  300,  299,  298,  297,  295,  294,  293,  282,  281,
      280,  278,  276,  275,  273,  272,  271,  270,  268,  266,
      265,  264,  262,  261,  260,  259,  257,  256,  254,  253,
      252,  251,  250,  249,  248,  247,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  233,  232,  230,
      229,  228,  227,  225,  224,  223,  222,  221,  220,  219,

      218,  216,  214,  213,  212,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  199,  197,  196,  195,  194,  193,
      191,  190,  189,  188,  187,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  151,  147,  145,  144,  143,  142,
      141,  140,  139,  138,  136,  135,  132,  129,  126,  123,
      121,  118,  117,  116,  115,  114,  113,  110,  109,  108,
      103,  102,  101,  100,   99,   98,   97,   96,   94,   93,
       92,   91,   90,   89,   79,   78,   77,   75,   74,   73,

       70,   68,   66,   62,   60,   58,   54,   44,   43,   39,
       37,   36,   31,   30,   23,   22,   21,   20,   19,   18,
       17,   16,   15,   14,    8,    3,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "kermo.lex"
#line 2 "kermo.lex"
/******************************************************************************
  This file is part of Arcade cabinet project.

  Copyright (C) 2014 ViP-PROTO Association, http://vip-proto.com
  Aleksandar Rikalo <aleksandar.rikalo@vip-proto.rs>

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License as
  published by the Free Software Foundation; either version 2 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
  02111-1307, USA.

  The GNU General Public License is contained in the file COPYING.
******************************************************************************/

#include "kermo.h"
#include "y.tab.h"
#include <stdio.h>

#line 801 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 31 "kermo.lex"

#line 985 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 514 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 627 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 32 "kermo.lex"
return OB;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "kermo.lex"
return CB;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 34 "kermo.lex"
return TITLE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "kermo.lex"
return EXE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 36 "kermo.lex"
return EXE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 37 "kermo.lex"
return EXE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 38 "kermo.lex"
return EXE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "kermo.lex"
return P1;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "kermo.lex"
return P2;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "kermo.lex"
return MOUSE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "kermo.lex"
return DEFAULT;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "kermo.lex"
return LUNCHER;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "kermo.lex"
return DIR;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "kermo.lex"
return GUI;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "kermo.lex"
return BGCOLOR;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "kermo.lex"
return ENTRYCOLOR;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "kermo.lex"
return SELCOLOR;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "kermo.lex"
return TEXTCOLOR;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "kermo.lex"
return SELTEXTCOLOR;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "kermo.lex"
return LOGOJPEG;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "kermo.lex"
return TIME_SORT_WEIGHT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "kermo.lex"
return STARTS_SORT_WEIGHT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "kermo.lex"
return TITLE_SORT_WEIGHT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "kermo.lex"
return POSITION_SORT_WEIGHT;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "kermo.lex"
return AUTORELOAD;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "kermo.lex"
{ yylval.n = THEME_VIPPROTO; return THEME; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "kermo.lex"
{ yylval.n = THEME_CALLIDUSCLOUD; return THEME; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "kermo.lex"
{ yylval.n = 1; return MULTIPLAYER; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "kermo.lex"
{ yylval.n = 0; return MULTIPLAYER; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "kermo.lex"
{ yylval.n = 1; return AUTOPICTURE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "kermo.lex"
{ yylval.n = 0; return AUTOPICTURE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "kermo.lex"
{ yylval.n = KEY_NONE; return KEY; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "kermo.lex"
{ yylval.n = KEY_MOUSE_UP; return KEY; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "kermo.lex"
{ yylval.n = KEY_MOUSE_DOWN; return KEY; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 66 "kermo.lex"
{ yylval.n = KEY_MOUSE_LEFT; return KEY; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 67 "kermo.lex"
{ yylval.n = KEY_MOUSE_RIGHT; return KEY; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 68 "kermo.lex"
{ yylval.n = KEY_LMOUSE; return KEY; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 69 "kermo.lex"
{ yylval.n = KEY_MMOUSE; return KEY; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 70 "kermo.lex"
{ yylval.n = KEY_RMOUSE; return KEY; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 71 "kermo.lex"
{ yylval.n = KEY_ESC; return KEY; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 72 "kermo.lex"
{ yylval.n = KEY_F1; return KEY; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 73 "kermo.lex"
{ yylval.n = KEY_F2; return KEY; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 74 "kermo.lex"
{ yylval.n = KEY_F3; return KEY; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 75 "kermo.lex"
{ yylval.n = KEY_F4; return KEY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 76 "kermo.lex"
{ yylval.n = KEY_F5; return KEY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 77 "kermo.lex"
{ yylval.n = KEY_F6; return KEY; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 78 "kermo.lex"
{ yylval.n = KEY_F7; return KEY; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 79 "kermo.lex"
{ yylval.n = KEY_F8; return KEY; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 80 "kermo.lex"
{ yylval.n = KEY_F9; return KEY; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 81 "kermo.lex"
{ yylval.n = KEY_F10; return KEY; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 82 "kermo.lex"
{ yylval.n = KEY_F11; return KEY; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 83 "kermo.lex"
{ yylval.n = KEY_F12; return KEY; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 84 "kermo.lex"
{ yylval.n = KEY_CONSOLE; return KEY; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 85 "kermo.lex"
{ yylval.n = KEY_1; return KEY; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 86 "kermo.lex"
{ yylval.n = KEY_2; return KEY; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 87 "kermo.lex"
{ yylval.n = KEY_3; return KEY; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 88 "kermo.lex"
{ yylval.n = KEY_4; return KEY; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 89 "kermo.lex"
{ yylval.n = KEY_5; return KEY; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 90 "kermo.lex"
{ yylval.n = KEY_6; return KEY; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 91 "kermo.lex"
{ yylval.n = KEY_7; return KEY; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 92 "kermo.lex"
{ yylval.n = KEY_8; return KEY; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 93 "kermo.lex"
{ yylval.n = KEY_9; return KEY; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 94 "kermo.lex"
{ yylval.n = KEY_0; return KEY; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 95 "kermo.lex"
{ yylval.n = KEY_MINUS; return KEY; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 96 "kermo.lex"
{ yylval.n = KEY_EQUAL; return KEY; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 97 "kermo.lex"
{ yylval.n = KEY_BACKSPACE; return KEY; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 98 "kermo.lex"
{ yylval.n = KEY_TAB; return KEY; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 99 "kermo.lex"
{ yylval.n = KEY_Q; return KEY; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 100 "kermo.lex"
{ yylval.n = KEY_W; return KEY; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 101 "kermo.lex"
{ yylval.n = KEY_E; return KEY; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 102 "kermo.lex"
{ yylval.n = KEY_R; return KEY; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 103 "kermo.lex"
{ yylval.n = KEY_T; return KEY; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 104 "kermo.lex"
{ yylval.n = KEY_Y; return KEY; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 105 "kermo.lex"
{ yylval.n = KEY_U; return KEY; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 106 "kermo.lex"
{ yylval.n = KEY_I; return KEY; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 107 "kermo.lex"
{ yylval.n = KEY_O; return KEY; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 108 "kermo.lex"
{ yylval.n = KEY_P; return KEY; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 109 "kermo.lex"
{ yylval.n = KEY_OPEN_SQB; return KEY; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 110 "kermo.lex"
{ yylval.n = KEY_CLOSE_SQB; return KEY; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 111 "kermo.lex"
{ yylval.n = KEY_ENTER; return KEY; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 112 "kermo.lex"
{ yylval.n = KEY_CAPS_LOCK; return KEY; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 113 "kermo.lex"
{ yylval.n = KEY_A; return KEY; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 114 "kermo.lex"
{ yylval.n = KEY_S; return KEY; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 115 "kermo.lex"
{ yylval.n = KEY_D; return KEY; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 116 "kermo.lex"
{ yylval.n = KEY_F; return KEY; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 117 "kermo.lex"
{ yylval.n = KEY_G; return KEY; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 118 "kermo.lex"
{ yylval.n = KEY_H; return KEY; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 119 "kermo.lex"
{ yylval.n = KEY_J; return KEY; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 120 "kermo.lex"
{ yylval.n = KEY_K; return KEY; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 121 "kermo.lex"
{ yylval.n = KEY_L; return KEY; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 122 "kermo.lex"
{ yylval.n = KEY_SEMI; return KEY; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 123 "kermo.lex"
{ yylval.n = KEY_QUOTE; return KEY; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 124 "kermo.lex"
{ yylval.n = KEY_L_SHIFT; return KEY; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 125 "kermo.lex"
{ yylval.n = KEY_R_SHIFT; return KEY; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 126 "kermo.lex"
{ yylval.n = KEY_Z; return KEY; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 127 "kermo.lex"
{ yylval.n = KEY_X; return KEY; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 128 "kermo.lex"
{ yylval.n = KEY_C; return KEY; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 129 "kermo.lex"
{ yylval.n = KEY_V; return KEY; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 130 "kermo.lex"
{ yylval.n = KEY_B; return KEY; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 131 "kermo.lex"
{ yylval.n = KEY_N; return KEY; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 132 "kermo.lex"
{ yylval.n = KEY_M; return KEY; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 133 "kermo.lex"
{ yylval.n = KEY_COMMA; return KEY; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 134 "kermo.lex"
{ yylval.n = KEY_POINT; return KEY; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 135 "kermo.lex"
{ yylval.n = KEY_SLASH; return KEY; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 136 "kermo.lex"
{ yylval.n = KEY_BACKSLASH; return KEY; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 137 "kermo.lex"
{ yylval.n = KEY_L_CTRL; return KEY; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 138 "kermo.lex"
{ yylval.n = KEY_L_WIN; return KEY; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 139 "kermo.lex"
{ yylval.n = KEY_L_ALT; return KEY; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 140 "kermo.lex"
{ yylval.n = KEY_SPACE; return KEY; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 141 "kermo.lex"
{ yylval.n = KEY_R_ALT; return KEY; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 142 "kermo.lex"
{ yylval.n = KEY_R_WIN; return KEY; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 143 "kermo.lex"
{ yylval.n = KEY_MENU; return KEY; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 144 "kermo.lex"
{ yylval.n = KEY_R_CTRL; return KEY; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 145 "kermo.lex"
{ yylval.n = KEY_INSERT; return KEY; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 146 "kermo.lex"
{ yylval.n = KEY_HOME; return KEY; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 147 "kermo.lex"
{ yylval.n = KEY_PGUP; return KEY; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 148 "kermo.lex"
{ yylval.n = KEY_DELETE; return KEY; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 149 "kermo.lex"
{ yylval.n = KEY_END; return KEY; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 150 "kermo.lex"
{ yylval.n = KEY_PGDOWN; return KEY; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 151 "kermo.lex"
{ yylval.n = KEY_UP; return KEY; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 152 "kermo.lex"
{ yylval.n = KEY_DOWN; return KEY; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 153 "kermo.lex"
{ yylval.n = KEY_LEFT; return KEY; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 154 "kermo.lex"
{ yylval.n = KEY_RIGHT; return KEY; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 155 "kermo.lex"
{ yylval.n = KEY_NUM_LOCK; return KEY; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 156 "kermo.lex"
{ yylval.n = KEY_NUM_SLASH; return KEY; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 157 "kermo.lex"
{ yylval.n = KEY_NUM_MUL; return KEY; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 158 "kermo.lex"
{ yylval.n = KEY_NUM_MINUS; return KEY; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 159 "kermo.lex"
{ yylval.n = KEY_NUM_7; return KEY; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 160 "kermo.lex"
{ yylval.n = KEY_NUM_8; return KEY; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 161 "kermo.lex"
{ yylval.n = KEY_NUM_9; return KEY; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 162 "kermo.lex"
{ yylval.n = KEY_NUM_PLUS; return KEY; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 163 "kermo.lex"
{ yylval.n = KEY_NUM_4; return KEY; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 164 "kermo.lex"
{ yylval.n = KEY_NUM_5; return KEY; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 165 "kermo.lex"
{ yylval.n = KEY_NUM_6; return KEY; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 166 "kermo.lex"
{ yylval.n = KEY_NUM_1; return KEY; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 167 "kermo.lex"
{ yylval.n = KEY_NUM_2; return KEY; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 168 "kermo.lex"
{ yylval.n = KEY_NUM_3; return KEY; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 169 "kermo.lex"
{ yylval.n = KEY_NUM_ENTER; return KEY; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 170 "kermo.lex"
{ yylval.n = KEY_NUM_0; return KEY; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 171 "kermo.lex"
{ yylval.n = KEY_NUM_DEL; return KEY; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 172 "kermo.lex"
{ sscanf(yytext, "%d", &yylval.n); return NUMBER; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 173 "kermo.lex"
{ sscanf(yytext + 2, "%x", &yylval.n); return COLOR; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 175 "kermo.lex"
{
                        int i;
                        yylval.s[0] = 0;
                        for (i = 0; yytext[i]; yylval.s[++i] = 0)
                           if (i > 0) yylval.s[i - 1] = yytext[i];
                        if (i > 1) yylval.s[i - 2] = 0;
                        return STRING;
                     }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 184 "kermo.lex"
{
                        int i;
                        yylval.s[0] = 0;
                        for (i = 0;yytext[i]; yylval.s[++i] = 0)
                           if (i > 0) yylval.s[i - 1]=yytext[i];
                        if (i > 1) yylval.s[i - 2] = 0;
                        return PSTRING;
                     }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 193 "kermo.lex"
{
                        int i;
                        yylval.s[0] = 0;
                        for (i = 0; yytext[i]; yylval.s[++i] = 0)
                           if (i > 0) yylval.s[i - 1] = yytext[i];
                        if (i > 1) yylval.s[i - 2] = 0;
                        return ISTRING;
                     }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 202 "kermo.lex"
{
                        int i;
                        yylval.s[0] = 0;
                        for (i = 0; yytext[i]; yylval.s[++i] = 0)
                           if (i > 0) yylval.s[i - 1] = yytext[i];
                        if (i > 0) yylval.s[i - 1] = 0;
                        return LSTRING;
                     }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 212 "kermo.lex"
{
                        warnk("Unkwown identifier %s, will be ignored!\n", yytext);
                        need_ussage_print = 1;
                     }
	YY_BREAK
case 148:
/* rule 148 can match eol */
YY_RULE_SETUP
#line 217 "kermo.lex"
{ }
	YY_BREAK
case 149:
/* rule 149 can match eol */
YY_RULE_SETUP
#line 218 "kermo.lex"
{ }
	YY_BREAK
case 150:
/* rule 150 can match eol */
YY_RULE_SETUP
#line 219 "kermo.lex"

	YY_BREAK
case 151:
YY_RULE_SETUP
#line 221 "kermo.lex"
ECHO;
	YY_BREAK
#line 1857 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 514 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 514 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 513);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 221 "kermo.lex"



